<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVxGZ83e\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVxGZ83e/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVxGZ83e.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVxGZ83e\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVxGZ83e\App_KernelDevDebugContainer([
    'container.build_hash' => 'VxGZ83e',
    'container.build_id' => 'cede954c',
    'container.build_time' => 1625641939,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVxGZ83e');
